name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Dependencies
      run: |
        cd Sneaker-head-app
        npm ci

    - name: Run Tests
      run: |
        cd Sneaker-head-app
        npm run test -- src/sum.test.js